haple = {
    {0, "Nose"},
    {1, "LEye"},
    {2, "REye"},
    {3, "LEar"},
    {4, "REar"},
    {5, "LShoulder"},
    {6, "RShoulder"},
    {7, "LElbow"},
    {8, "RElbow"},
    {9, "LWrist"},
    {10, "RWrist"},
    {11, "LHip"},
    {12, "RHip"},
    {13, "LKnee"},
    {14, "Rknee"},
    {15, "LAnkle"},
    {16, "RAnkle"},
    {17, "Head"},
    {18, "Neck"},
    {19, "Hip"},
    {20, "LBigToe"},
    {21, "RBigToe"},
    {22, "LSmallToe"},
    {23, "RSmallToe"},
    {24, "LHeel"},
    {25, "RHeel"}
}


body25 = {
    {0, "Nose"},
    {1, "Neck"},
    {2, "RShoulder"},
    {3, "RElbow"},
    {4, "RWrist"},
    {5, "LShoulder"},
    {6, "LElbow"},
    {7, "LWrist"},
    {8, "Hip"},
    {9, "RHip"},
    {10, "Rknee"},
    {11, "Rknee"},
    {12, "LHip"},
    {13, "LKnee"},
    {14, "LAnkle"},
    {15, "REye"},
    {16, "LEye"},
    {17, "REar"},
    {18, "LEar"},
    {19, "LBigToe"},
    {20, "LSmallToe"},
    {21, "LHeel"},
    {22, "RBigToe"},
    {23, "RSmallToe"},
    {24, "RHeel"},
}

h36m = {
    {0, "Hip"},
    {1, "RHip"},
    {2, "Rknee"},
    {3, "RAnkle"},
    {4, "LHip"},
    {5, "LKnee"},
    {6, "LAnkle"},
    {7, "Spine"},
    {8, "Neck"},
    {9, "Nose"},
    {10, "Head"},
    {11, "LShoulder"},
    {12, "LElbow"},
    {13, "LWrist"},
    {14, "RShoulder"},
    {15, "RElbow"},
    {16, "RWrist"},
}

coco17 = {
    {0, "Nose"},
    {1, "LEye"},
    {2, "REye"},
    {3, "LEar"},
    {4, "REar"},
    {5, "LShoulder"},
    {6, "RShoulder"},
    {7, "LElbow"},
    {8, "RElbow"},
    {9, "LWrist"},
    {10, "RWrist"},
    {11, "LHip"},
    {12, "RHip"},
    {13, "LKnee"},
    {14, "Rknee"},
    {15, "LAnkle"},
    {16, "RAnkle"},
}

